services:
  ollama:
    image: ollama/ollama:latest
    mem_limit: 12g
    ports:
      - "11434:11434"
    environment:
      - OLLAMA_HOST=0.0.0.0
    volumes:
      - ollama_data:/root/.ollama
    container_name: ollama
    pull_policy: always
    tty: true
    restart: always
    entrypoint: ["/bin/sh", "-c"]
    command:
      - |
        /bin/ollama serve & 
        sleep 5 && 
        echo '🔴 Retrieving model...' && 
        ollama pull qwen2.5:14b && 
        echo '🟢 Done!' && 
        wait

  app:
    build: .
    depends_on:
      - ollama
    environment:
      - OLLAMA_BASE_URL=http://ollama:11434
    volumes:
      - .:/app
    container_name: titan-app
    ports:
      - "8501:8501"
    command: ["streamlit", "run", "src/app.py"]

volumes:
  ollama_data:
